name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2

            - name: Setup Python 3.10
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.10'
            
            - name: Run tests
              run: python -m unittest tests/test*.py -vv